AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Library of functions to convert binary timeseries data to JTS

Globals:
  Function:
    Timeout: 3
    Runtime: nodejs16.x
    Architectures:
      - x86_64
    MemorySize: 128

Resources:
  Sample:
    Type: AWS::Serverless::Function
    Properties:
      Description: Sample CSV
      Handler: index.sampleConverter
      Policies:
        - AWSLambdaBasicExecutionRole
      Tags:
        Scope: private
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - index.ts
  QuantAqModulair:
    Type: AWS::Serverless::Function
    Properties:
      Description: QuantAQ MODULAIR
      Handler: index.quantAqModulairConverter
      Policies:
        - AWSLambdaBasicExecutionRole
      Tags:
        Scope: public
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - index.ts
  AecomVibration:
    Type: AWS::Serverless::Function
    Properties:
      Description: AECOM Vibration Sensor
      Handler: index.aecomVibrationConverter
      Policies:
        - AWSLambdaBasicExecutionRole
      Tags:
        Scope: private
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - index.ts
  AecomNoise:
    Type: AWS::Serverless::Function
    Properties:
      Description: AECOM Noise Sensor
      Handler: index.aecomNoiseConverter
      Policies:
        - AWSLambdaBasicExecutionRole
      Tags:
        Scope: private
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - index.ts
