AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Library of functions to convert binary timeseries data to JTS

Globals:
  Function:
    Timeout: 60
    Runtime: nodejs20.x
    Architectures:
      - x86_64
    MemorySize: 768

Resources:
  Sample:
    Type: AWS::Serverless::Function
    Properties:
      Description: Sample CSV
      Handler: index.sampleConverter
      Policies:
        - AWSLambdaBasicExecutionRole
      Tags:
        Scope: private
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - index.ts
  SampleWithZone:
    Type: AWS::Serverless::Function
    Properties:
      Description: Sample With Zone CSV
      Handler: index.sampleConverter
      Policies:
        - AWSLambdaBasicExecutionRole
      Tags:
        Scope: private
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - index.ts
  QuantAqModulair:
    Type: AWS::Serverless::Function
    Properties:
      Description: QuantAQ MODULAIR
      Handler: index.quantAqModulairConverter
      Policies:
        - AWSLambdaBasicExecutionRole
      Tags:
        Scope: public
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - index.ts
  SyscomVibration:
    Type: AWS::Serverless::Function
    Properties:
      Description: Syscom MR3000BLA
      Handler: index.syscomVibrationConverter
      Policies:
        - AWSLambdaBasicExecutionRole
      Tags:
        Scope: private
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - index.ts
  CubeNoise:
    Type: AWS::Serverless::Function
    Properties:
      Description: 01dB CUBE
      Handler: index.cubeNoiseConverter
      Policies:
        - AWSLambdaBasicExecutionRole
      Tags:
        Scope: private
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - index.ts
  ImgwMet:
    Type: AWS::Serverless::Function
    Properties:
      Description: IMGW Meteorological
      Handler: index.imgwMetConverter
      Policies:
        - AWSLambdaBasicExecutionRole
      Tags:
        Scope: private
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - index.ts
  DanoneCortex:
    Type: AWS::Serverless::Function
    Properties:
      Description: Danone Cortex
      Handler: index.danoneCortexConverter
      Policies:
        - AWSLambdaBasicExecutionRole
      Tags:
        Scope: private
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - index.ts
  KolibriCloud:
    Type: AWS::Serverless::Function
    Properties:
      Description: Kolibri Cloud
      Handler: index.kolibriCloudConverter
      Policies:
        - AWSLambdaBasicExecutionRole
      Tags:
        Scope: private
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - index.ts
  AcoemFusion:
    Type: AWS::Serverless::Function
    Properties:
      Description: Acoem Fusion
      Handler: index.acoemFusionConverter
      Policies:
        - AWSLambdaBasicExecutionRole
      Tags:
        Scope: private
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - index.ts
  DASCaptisV2:
    Type: AWS::Serverless::Function
    Properties:
      Description: DAS Captis V2
      Handler: index.dasCaptisV2Converter
      Policies:
        - AWSLambdaBasicExecutionRole
      Tags:
        Scope: private
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - index.ts
  DanoneRubix:
    Type: AWS::Serverless::Function
    Properties:
      Description: Danone Rubix
      Handler: index.danoneRubixConverter
      Policies:
        - AWSLambdaBasicExecutionRole
      Tags:
        Scope: private
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - index.ts
  SiemensLogoPlc:
    Type: AWS::Serverless::Function
    Properties:
      Description: Siemens Logo PLC
      Handler: index.siemensLogoPlcConverter
      Policies:
        - AWSLambdaBasicExecutionRole
      Tags:
        Scope: private
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - index.ts
